pipeline {
     agent any
     stages {
        stage("Build") {
            steps {
                 sh "apt install sudo"
                sh "sudo npm install"
                sh "sudo npm run build"
            }
        }

    }
}
